### PR TITLE
Extension :unscoped option (boolean -> String/Class/Symbol)

### PR DESCRIPTION
**Pull request by shipiev**
#before 
belongs_to :product, unscoped: true # ok
has_one :project, through: :product  # unscoped don't work

#after
belongs_to :product, unscoped: true # ok
has_one :project, through: :product, uncoped: :product  # ok

### CODE REVIEW

**Comment by markets** [comment]
Hi @shipiev, thanks for this :+1: 

Actually `through` option is not "officaly" supported (not documented) and I'm not sure if we really should support it. At least, to introduce new features we need some tests to be sure new stuff works and we don't break anything.  

On the other hand, since Rails 4 (ActiveRecord 4) there are some native ways to unscope objects via associations (via a scope block, new unscope method, unscoped), although there are some related issues too... as you can see follwing: https://github.com/rails/rails/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+unscope, https://github.com/rails/rails/pulls?q=is%3Aopen+unscope+is%3Apr

Seems to deal with `default_scope` is kind of hard (see also https://github.com/markets/unscoped_associations/issues/6#issuecomment-98875864)... So in case we add this feature, we should add tests. Did you try to use any native way + through option in Rails4+ projects? It also breaks? Or are you in Rails 3?

Thanks! Keep in touch.
 
PS. My plan is to keep this plugin for Rails 3 and Rails 4 (kind of support for transition/migration paths), but hopefully in Rails 5 will be not necessary at all using the internal API.

**Comment by shipiev** [comment]
I develop plugins for Redmine 2.6 (Rails 3.2).

**Comment by markets** [comment]
@shipiev I hope you understand that we need to add new tests to the current CI suite to be sure what use cases are you trying to support with this PR and to ensure no breakages with future changes.

**Comment by shipiev** [comment]
@markets Ok, but I will have to modify the schema (add through association for Vote)

**Comment by markets** [comment]
@shipiev yes, no problem, modify schema and models to accomodate new specs :+1: 

This way, will help a lot to understand exactly what problem are you trying to solve/support. Thanks.

**Pull request closed without merging**
